/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSobreRouteImport } from './routes/_site.sobre'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as SiteAreasTrabalhistaRouteImport } from './routes/_site.areas.trabalhista'
import { Route as SiteAreasPrevidenciarioRouteImport } from './routes/_site.areas.previdenciario'
import { Route as SiteAreasFamiliaRouteImport } from './routes/_site.areas.familia'
import { Route as SiteAreasCivelRouteImport } from './routes/_site.areas.civel'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSobreRoute = SiteSobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAreasTrabalhistaRoute = SiteAreasTrabalhistaRouteImport.update({
  id: '/areas/trabalhista',
  path: '/areas/trabalhista',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAreasPrevidenciarioRoute = SiteAreasPrevidenciarioRouteImport.update({
  id: '/areas/previdenciario',
  path: '/areas/previdenciario',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAreasFamiliaRoute = SiteAreasFamiliaRouteImport.update({
  id: '/areas/familia',
  path: '/areas/familia',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAreasCivelRoute = SiteAreasCivelRouteImport.update({
  id: '/areas/civel',
  path: '/areas/civel',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contato': typeof SiteContatoRoute
  '/sobre': typeof SiteSobreRoute
  '/areas/civel': typeof SiteAreasCivelRoute
  '/areas/familia': typeof SiteAreasFamiliaRoute
  '/areas/previdenciario': typeof SiteAreasPrevidenciarioRoute
  '/areas/trabalhista': typeof SiteAreasTrabalhistaRoute
}
export interface FileRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/contato': typeof SiteContatoRoute
  '/sobre': typeof SiteSobreRoute
  '/': typeof SiteIndexRoute
  '/areas/civel': typeof SiteAreasCivelRoute
  '/areas/familia': typeof SiteAreasFamiliaRoute
  '/areas/previdenciario': typeof SiteAreasPrevidenciarioRoute
  '/areas/trabalhista': typeof SiteAreasTrabalhistaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_site/contato': typeof SiteContatoRoute
  '/_site/sobre': typeof SiteSobreRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/areas/civel': typeof SiteAreasCivelRoute
  '/_site/areas/familia': typeof SiteAreasFamiliaRoute
  '/_site/areas/previdenciario': typeof SiteAreasPrevidenciarioRoute
  '/_site/areas/trabalhista': typeof SiteAreasTrabalhistaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/contato'
    | '/sobre'
    | '/areas/civel'
    | '/areas/familia'
    | '/areas/previdenciario'
    | '/areas/trabalhista'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sitemap.xml'
    | '/contato'
    | '/sobre'
    | '/'
    | '/areas/civel'
    | '/areas/familia'
    | '/areas/previdenciario'
    | '/areas/trabalhista'
  id:
    | '__root__'
    | '/_site'
    | '/sitemap.xml'
    | '/_site/contato'
    | '/_site/sobre'
    | '/_site/'
    | '/_site/areas/civel'
    | '/_site/areas/familia'
    | '/_site/areas/previdenciario'
    | '/_site/areas/trabalhista'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sobre': {
      id: '/_site/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SiteSobreRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/areas/trabalhista': {
      id: '/_site/areas/trabalhista'
      path: '/areas/trabalhista'
      fullPath: '/areas/trabalhista'
      preLoaderRoute: typeof SiteAreasTrabalhistaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/areas/previdenciario': {
      id: '/_site/areas/previdenciario'
      path: '/areas/previdenciario'
      fullPath: '/areas/previdenciario'
      preLoaderRoute: typeof SiteAreasPrevidenciarioRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/areas/familia': {
      id: '/_site/areas/familia'
      path: '/areas/familia'
      fullPath: '/areas/familia'
      preLoaderRoute: typeof SiteAreasFamiliaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/areas/civel': {
      id: '/_site/areas/civel'
      path: '/areas/civel'
      fullPath: '/areas/civel'
      preLoaderRoute: typeof SiteAreasCivelRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteContatoRoute: typeof SiteContatoRoute
  SiteSobreRoute: typeof SiteSobreRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteAreasCivelRoute: typeof SiteAreasCivelRoute
  SiteAreasFamiliaRoute: typeof SiteAreasFamiliaRoute
  SiteAreasPrevidenciarioRoute: typeof SiteAreasPrevidenciarioRoute
  SiteAreasTrabalhistaRoute: typeof SiteAreasTrabalhistaRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteContatoRoute: SiteContatoRoute,
  SiteSobreRoute: SiteSobreRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteAreasCivelRoute: SiteAreasCivelRoute,
  SiteAreasFamiliaRoute: SiteAreasFamiliaRoute,
  SiteAreasPrevidenciarioRoute: SiteAreasPrevidenciarioRoute,
  SiteAreasTrabalhistaRoute: SiteAreasTrabalhistaRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
